#include "ulog.h"
#include <lely/co/co.h>
#include <lely/co/csdo.h>
#include <lely/co/nmt.h>
#include <lely/co/rpdo.h>
#include <lely/co/tpdo.h>
#include <lely/co/sdev.h>
#include <lely/co/sdo.h>
#include <lely/co/csdo.h>
#include <lely/co/dcf.h>

#include <lely/co/time.h>
#include <lely/util/diag.h>

#include <assert.h>
#include <time.h>
#include <stdlib.h>
#include <unistd.h> /* read(), close() */
#include <pthread.h>

#include "bsp/bsp_can.h"
#include "libcia402/include/statemachine.h"
#include <fcntl.h>
#include "callbacks/indication.h"
#include "callbacks/co_hooks.h"
#include "osal/canopen/csdo.h"
// Generated by `dcf2c --no-strings lpc17xx.dcf lpc17xx_sdev -o src/sdev.c`
extern const struct co_sdev master_sdev;

int can_sock;

static inline long diff_ms(const struct timespec *a, const struct timespec *b) {
  return (a->tv_sec - b->tv_sec) * 1000L + (a->tv_nsec - b->tv_nsec) / 1000000L;
}

void send_homing_sequence(can_net_t *net, co_dev_t *dev)
{
  //co_csdo_t *csdo = co_csdo_create(net, NULL, 2);
  // Configure the slave to monitor the heartbeat of the master (node-ID 1)
  // with a timeout of 2000 ms.
/*
  if (csdo_dn_value(net,dev,1,0x1016,0,(1 << 16) | 2000) !=0)
  {
    ulog_error("heartbeat observer sdo rejected");
  }
  */

  ulog_info(" Configurintg Slave heartbeat");
  int heartbeat_time=1000;
  co_csdo_t *csdo = co_csdo_create(net, NULL, 2);
  if (co_csdo_dn_val_req(csdo,0x1017,0,CO_DEFTYPE_UNSIGNED16,&heartbeat_time,NULL,NULL) != 0)
  {
    ulog_error("Failed to configure heartbeat time %s",errc2str(get_errc()));
  }
  co_csdo_destroy(csdo);
  for (int i=0;i<3;i++)
  {
    const int vals[3]={6, 7, 0xF}; // Double-braces required in C++11 prior to
    csdo_dn_value(net,dev,1,0x6040,0,vals[i]);
  }

  // Configure Homing
  void* data;
  csdo_dn_value(net,dev,1,0x6060,0,0x6);
  csdo_dn_value(net,dev,1,0x6098,0,0x1);
  csdo_dn_value(net,dev,1,0x609A,0,100);
  csdo_dn_value(net,dev,1,0x6099,0,250);
  csdo_dn_value(net,dev,1,0x6060,0,0xF6);

}

void debug_sync_indication(co_nmt_t *nmt, co_unsigned8_t cnt, void *data) {
  ulog_topic_info("Sync","Sync Event occcurred");
}
int main(int argc, char** argv) {

  char buf[128];

  char* can_if=argv[1];
  char* dcf=argv[2];
  printf("interface = %s, dcf = %s\r\n",can_if,dcf);
  can_sock = can_open(can_if);

  can_net_t *net = can_net_create();
  assert(net);
  can_net_set_send_func(net, &on_can_send, NULL);

  struct timespec now = {0, 0};
  struct timespec last = {0, 0};
  struct timespec tx_time = {0, 0};

//  clock_gettime(CLOCK_MONOTONIC, &now);
  timespec_get(&now, TIME_UTC);
  can_net_set_time(net, &now);

//  can_net_set_time(net, &now);
  co_dev_t *dev = co_dev_create_from_dcf_file(dcf);
  //  assert(dev);
  // Create the CANopen NMT service.
  co_nmt_t *nmt = co_nmt_create(net, dev);
  assert(nmt);
  int rc =co_nmt_cs_ind(nmt, CO_NMT_CS_RESET_NODE);
  if (rc != 0)
  {
    ulog_error("Failed to reset node");
  }
//  co_nmt_set_cs_ind(nmt, &on_nmt_cs, NULL);
  //co_time_set_ind(co_nmt_get_time(nmt), &on_time, NULL);
// RPDO_1 : 0x1800 + Mapping@ 0x1a00
  co_tpdo_t *tpdo_1 = co_tpdo_create(net, dev, 1);
  if (tpdo_1 == NULL) {
    ulog_error("tdpo 1 not created");
  }

  if (co_tpdo_start(tpdo_1) != 0) {
    ulog_error("could not start tpdo");
  }
// TPDO_1 : 0x1600 + Mapping@ 0x1600
  co_rpdo_t *rpdo_1 = co_rpdo_create(net, dev, 1);
    if (rpdo_1 == NULL) {
      ulog_error("rdpo 1 not created");
    }

  if (co_rpdo_start(rpdo_1) != 0) {
    ulog_error("could not start rpdo");
  }

  if (co_rpdo_sync(rpdo_1, 1) != 0) {
    ulog_error("rpdo could not be configured with sync");
  }

  if (co_tpdo_sync(tpdo_1, 1) != 0) {
   ulog_error("sync service not working");
  }  co_nmt_on_sync(nmt, 1);

  co_obj_t * obj = co_dev_find_obj(dev, 0x1017);
  uint16_t statusword=500;
  co_obj_set_val(obj, 0x00,&statusword, sizeof(statusword));

  rc = co_nmt_cfg_req(nmt,2,1000,NULL,NULL);
if (rc !=0)
{
  ulog_error("Failed to send configuration %s",errc2str(get_errc()));
}
  co_nmt_cs_req(nmt,CO_NMT_CS_START,2);
//  co_nmt_boot_req(nmt,2,1000);
//  co_nmt_set_sync_ind(nmt,debug_sync_indication,NULL);
  for (;;) {
    // Update the CAN network clock.
//    timespec_get(&now,TIME_UTC);
    //clock_gettime(CLOCK_MONOTONIC, &now);
//    can_net_set_time(net, &now);
    // Process any received CAN frames.
    struct can_msg msg;
    int n_frames = can_recv(&msg, 1);
    if (n_frames != 0) {
      can_net_recv(net, &msg);
    }
char c;
   while( (c = getchar()) !='.')
   {
     ulog_info("Gelesen");
     send_homing_sequence(net,dev);

   }
  }
  co_nmt_destroy(nmt);
  co_dev_destroy(dev);
  can_net_destroy(net);
  return 0;
}