#include "ulog.h"
#include <lely/co/co.h>
#include <lely/co/csdo.h>
#include <lely/co/nmt.h>
#include <lely/co/rpdo.h>
#include <lely/co/tpdo.h>
#include <lely/co/sdev.h>
#include <lely/co/sdo.h>
#include <lely/co/csdo.h>
#include <lely/co/dcf.h>

#include <lely/co/time.h>
#include <lely/util/diag.h>

#include <assert.h>
#include <time.h>
#include <stdlib.h>
#include <unistd.h> /* read(), close() */
#include <pthread.h>

#include "bsp/bsp_can.h"
#include "libcia402/include/statemachine.h"
#include <fcntl.h>
#include "callbacks/indication.h"
#include "callbacks/co_hooks.h"
#include "osal/canopen/csdo.h"
// Generated by `dcf2c --no-strings lpc17xx.dcf lpc17xx_sdev -o src/sdev.c`
extern const struct co_sdev master_sdev;

int can_sock;

static inline long diff_ms(const struct timespec *a, const struct timespec *b) {
  return (a->tv_sec - b->tv_sec) * 1000L + (a->tv_nsec - b->tv_nsec) / 1000000L;
}

void send_sdo(can_net_t *net, co_dev_t *dev,int idx,int val)
{
  co_csdo_t *csdo = co_csdo_create(net, dev, 1);
  int value=val;
  co_csdo_dn_val_req(csdo,idx,0,CO_DEFTYPE_UNSIGNED32,&value,NULL,NULL);
  co_csdo_destroy(csdo);
}
void send_homing_sequence(can_net_t *net, co_dev_t *dev)
{

  for (int i=0;i<3;i++)
  {
    co_csdo_t *csdo = co_csdo_create(net, dev, 1);
    const int vals[3]={6, 7, 0xF}; // Double-braces required in C++11 prior to
    int value=vals[i];
    co_csdo_dn_val_req(csdo,0x6040,0,CO_DEFTYPE_UNSIGNED32,&value,NULL,NULL);
    co_csdo_destroy(csdo);
  }

  // Configure Homing
  void* data;

  send_sdo(net,dev,0x6060,0x6);
  send_sdo(net,dev,0x6098,0x1);
  send_sdo(net,dev,0x609A,100);
  send_sdo(net,dev,0x6099,250);
  send_sdo(net,dev,0x6060,0xF6);

}

void debug_sync_indication(co_nmt_t *nmt, co_unsigned8_t cnt, void *data) {
  ulog_topic_info("Sync","Sync Event occcurred");
}
int main(int argc, char** argv) {

  char buf[128];

  char* can_if=argv[1];
  char* dcf=argv[2];
  printf("interface = %s, dcf = %s\r\n",can_if,dcf);
  can_sock = can_open(can_if);

  can_net_t *net = can_net_create();
  assert(net);
  can_net_set_send_func(net, &on_can_send, NULL);

  struct timespec now = {0, 0};
  struct timespec last = {0, 0};
  struct timespec tx_time = {0, 0};

//  clock_gettime(CLOCK_MONOTONIC, &now);
  timespec_get(&now, TIME_UTC);
  can_net_set_time(net, &now);

//  can_net_set_time(net, &now);
  co_dev_t *dev = co_dev_create_from_dcf_file(dcf);
  //  assert(dev);
  // Create the CANopen NMT service.
  co_nmt_t *nmt = co_nmt_create(net, dev);
  assert(nmt);
// Also sends 130 to Node 0;
  int rc =co_nmt_cs_ind(nmt, CO_NMT_CS_RESET_NODE);
  if (rc != 0)
  {
    ulog_error("Failed to reset node");
  }
  co_nmt_cs_req(nmt,CO_NMT_CS_START,2);


  //  │../../../src/co/nmt.c:1843: debug: NMT: sending command specifier 130 to node 0
  //co_nmt_cs_req(nmt,CO_NMT_CS_RESET_COMM,0);

//  co_nmt_set_cs_ind(nmt, &on_nmt_cs, NULL);
  //co_time_set_ind(co_nmt_get_time(nmt), &on_time, NULL);
// RPDO_1 : 0x1800 + Mapping@ 0x1a00
/*
  co_obj_t * obj = co_dev_find_obj(dev, 0x1017);
  uint16_t statusword=500;
  co_obj_set_val(obj, 0x00,&statusword, sizeof(statusword));

  rc = co_nmt_cfg_req(nmt,2,1000,NULL,NULL);
if (rc !=0)
{
  ulog_error("Failed to send configuration %s",errc2str(get_errc()));
}
  co_nmt_cs_req(nmt,CO_NMT_CS_START,2);
  if (co_nmt_boot_req(nmt,2,1000) != 0)
  {
    ulog_info("Boot request returned %s", errc2str(get_errc()));
  }
  if (co_nmt_is_booting(nmt,2))
  {
    ulog_info("Slave is still booting");
  }
  else
  {
    ulog_info("Slave already booting / not booting");
  }
*/
//  co_nmt_set_sync_ind(nmt,debug_sync_indication,NULL);
  for (;;) {
    // Update the CAN network clock.
//    timespec_get(&now,TIME_UTC);
    //clock_gettime(CLOCK_MONOTONIC, &now);
//    can_net_set_time(net, &now);
    // Process any received CAN frames.
    struct can_msg msg;
    int n_frames = can_recv(&msg, 1);
    if (n_frames != 0) {
      can_net_recv(net, &msg);
    }
char c;
   while( (c = getchar()) !='.')
   {
     ulog_info("Gelesen");
     send_homing_sequence(net,dev);

   }
  }
  co_nmt_destroy(nmt);
  co_dev_destroy(dev);
  can_net_destroy(net);
  return 0;
}