#include "ulog/ulog.h"
#include <lely/co/co.h>
#include <lely/co/csdo.h>
#include <lely/co/nmt.h>
#include <lely/co/rpdo.h>
#include <lely/co/tpdo.h>
#include <lely/co/sdev.h>
#include <lely/co/sdo.h>
#include <lely/co/csdo.h>
#include <lely/co/dcf.h>

#include <lely/co/time.h>
#include <lely/util/diag.h>

#include <assert.h>
#include <time.h>
#include <stdlib.h>
#include <unistd.h> /* read(), close() */
#include <pthread.h>

#include "bsp/bsp_can.h"
#include "libcia402/include/statemachine.h"
#include "callbacks/indication.h"
#include "callbacks/co_hooks.h"

// Generated by `dcf2c --no-strings lpc17xx.dcf lpc17xx_sdev -o src/sdev.c`
extern const struct co_sdev master_sdev;

int can_sock;

static inline long diff_ms(const struct timespec *a, const struct timespec *b) {
  return (a->tv_sec - b->tv_sec) * 1000L + (a->tv_nsec - b->tv_nsec) / 1000000L;
}


int main(int argc, char** argv) {
  char* can_if=argv[1];
  char* dcf=argv[2];
  printf("interface = %s, dcf = %s\r\n",can_if,dcf);
  ulog_topic_config(true);
  can_sock = can_open(can_if);

  can_net_t *net = can_net_create();
  assert(net);
  can_net_set_send_func(net, &on_can_send, NULL);

  struct timespec now = {0, 0};
  struct timespec last = {0, 0};
  struct timespec tx_time = {0, 0};

  clock_gettime(CLOCK_MONOTONIC, &now);
//  can_net_set_time(net, &now);

  // Create a dynamic object dictionary from the static object dictionary
 //co_dev_t* dev = co_dev_create(1);
  co_dev_t *dev = co_dev_create_from_dcf_file(dcf);
  //  assert(dev);
 uint16_t min=1,max=127;
  //co_dev_read_dcf_file(dev,&min,&max,"master.dcf");
  // Create the CANopen NMT service.
  co_nmt_t *nmt = co_nmt_create(net, dev);
  assert(nmt);

  co_nmt_cs_ind(nmt, CO_NMT_CS_RESET_NODE);
  co_nmt_set_cs_ind(nmt, &on_nmt_cs, NULL);
//  co_time_set_ind(co_nmt_get_time(nmt), &on_time, NULL);
// RPDO_1 : 0x1800 + Mapping@ 0x1a00
  co_tpdo_t *tpdo_1 = co_tpdo_create(net, dev, 1);
  if (tpdo_1 == NULL) {
    ulog_error("tdpo 1 not created");
  }

  if (co_tpdo_start(tpdo_1) != 0) {
    ulog_error("could not start tpdo");
  }
// TPDO_1 : 0x1600 + Mapping@ 0x1600
  co_rpdo_t *rpdo_1 = co_rpdo_create(net, dev, 1);
    if (rpdo_1 == NULL) {
      ulog_error("rdpo 1 not created");
    }

  if (co_rpdo_start(rpdo_1) != 0) {
    ulog_error("could not start rpdo");
  }

  if (co_rpdo_sync(rpdo_1, 1) != 0) {
    ulog_error("rpdo could not be configured with sync");
  }

  void *pdata;
  void *p_tx_data;
  void *p_sync_data;
  if (co_tpdo_sync(tpdo_1, 1) != 0) {
   ulog_error("sync service not working");
  }  co_nmt_on_sync(nmt, 1);

  uint32_t val=0xF;
  co_unsigned16_t idx=0x6040;
  co_unsigned8_t subidx=0x00;

  for (int i=0;i<3;i++)
  {
    const int vals[3]={6, 7, 0xF}; // Double-braces required in C++11 prior to
    val=vals[i];
    co_csdo_t *csdo = co_csdo_create(net, dev, 1);
    assert(csdo);
    if (co_csdo_dn_val_req(csdo,idx,subidx,CO_DEFTYPE_UNSIGNED32,&val,NULL,NULL) <0 )
    {
      ulog_error("Failed to send sdo to server %s",errc2str(get_errc()));
    }
    co_csdo_destroy(csdo);
//    std::printf("Slave progressed to %04x\r\n",Wait(AsyncRead<uint32_t>(0x6041,0)));
  }
  // Configure Homing
  val=6;
  co_csdo_t *csdo = co_csdo_create(net, dev, 1);
  if (co_csdo_dn_val_req(csdo,0x6060,0,CO_DEFTYPE_UNSIGNED32,&val,NULL,NULL) <0)
  {
    ulog_error("Failed request MoOp 'Homing' %s",errc2str(get_errc()));
  }
  co_csdo_destroy(csdo);
/*
  co_csdo_dn_val_req(csdo,0x6098,0,CO_DEFTYPE_UNSIGNED32,(void*)1,NULL,NULL);
  co_csdo_dn_val_req(csdo,0x609A,0,CO_DEFTYPE_UNSIGNED32,(void*)100,NULL,NULL);
  co_csdo_dn_val_req(csdo,0x6099,0,CO_DEFTYPE_UNSIGNED32,(void*)300,NULL,NULL);
  */
  for (;;) {
    // Update the CAN network clock.
    clock_gettime(CLOCK_MONOTONIC, &now);
//    can_net_set_time(net, &now);
    // Process any received CAN frames.
    struct can_msg msg;
    int n_frames = can_recv(&msg, 1);
    if (n_frames != 0) {
      can_net_recv(net, &msg);
    }

    if (diff_ms(&now, &last) >= 1000) {
      last = now;
    }
  }
  co_nmt_destroy(nmt);
  co_dev_destroy(dev);
  can_net_destroy(net);
  return 0;
}