#include <lely/co/sdev.h>
#define CO_SDEV_STRING(s) s
const struct co_sdev lpc17xx_sdev = {
    .id = 0x2,
    .name = NULL,
    .vendor_name = CO_SDEV_STRING("Lely Industries N.V."),
    .vendor_id = 0x00000360,
    .product_name = NULL,
    .product_code = 0x00000000,
    .revision = 0x00000000,
    .order_code = NULL,
    .baud = 0 | CO_BAUD_1000 | CO_BAUD_800 | CO_BAUD_500 | CO_BAUD_250 |
            CO_BAUD_125 | CO_BAUD_50 | CO_BAUD_20 | CO_BAUD_10,
    .rate = 0,
    .lss = 1,
    .dummy = 0x0f7f00fe,
    .nobj = 18, // 16,
    .objs = (const struct co_sobj[]){
        {.name = CO_SDEV_STRING("Device type"),
         .idx = 0x1000,
         .code = CO_OBJECT_VAR,
         .nsub = 1,
         .subs =
             (const struct co_ssub[]){{.name = CO_SDEV_STRING("Device type"),
                                       .subidx = 0x00,
                                       .type = CO_DEFTYPE_UNSIGNED32,
                                       .min = {.u32 = CO_UNSIGNED32_MIN},
                                       .max = {.u32 = CO_UNSIGNED32_MAX},
                                       .def = {.u32 = CO_UNSIGNED32_MIN},
                                       .val = {.u32 = CO_UNSIGNED32_MIN},
                                       .access = CO_ACCESS_RO,
                                       .pdo_mapping = 0,
                                       .flags = 0}}},
        {.name = CO_SDEV_STRING("Error register"),
         .idx = 0x1001,
         .code = CO_OBJECT_VAR,
         .nsub = 1,
         .subs =
             (const struct co_ssub[]){{.name = CO_SDEV_STRING("Error register"),
                                       .subidx = 0x00,
                                       .type = CO_DEFTYPE_UNSIGNED8,
                                       .min = {.u8 = CO_UNSIGNED8_MIN},
                                       .max = {.u8 = CO_UNSIGNED8_MAX},
                                       .def = {.u8 = CO_UNSIGNED8_MIN},
                                       .val = {.u8 = CO_UNSIGNED8_MIN},
                                       .access = CO_ACCESS_RO,
                                       .pdo_mapping = 0,
                                       .flags = 0}}},
        {.name = CO_SDEV_STRING("COB-ID SYNC message"),
         .idx = 0x1005,
         .code = CO_OBJECT_VAR,
         .nsub = 1,
         .subs = (const struct co_ssub[]){{.name = CO_SDEV_STRING(
                                               "COB-ID SYNC message"),
                                           .subidx = 0x00,
                                           .type = CO_DEFTYPE_UNSIGNED32,
                                           .min = {.u32 = CO_UNSIGNED32_MIN},
                                           .max = {.u32 = CO_UNSIGNED32_MAX},
                                           .def = {.u32 = 0x00000080lu},
                                           .val = {.u32 = 0x00000080lu},
                                           .access = CO_ACCESS_RW,
                                           .pdo_mapping = 0,
                                           .flags = 0}}},
        {.name = CO_SDEV_STRING("COB-ID EMCY"),
         .idx = 0x1014,
         .code = CO_OBJECT_VAR,
         .nsub = 1,
         .subs =
             (const struct co_ssub[]){{.name = CO_SDEV_STRING("COB-ID EMCY"),
                                       .subidx = 0x00,
                                       .type = CO_DEFTYPE_UNSIGNED32,
                                       .min = {.u32 = CO_UNSIGNED32_MIN},
                                       .max = {.u32 = CO_UNSIGNED32_MAX},
                                       .def = {.u32 = 0x0000017flu},
                                       .val = {.u32 = 0x0000017flu},
                                       .access = CO_ACCESS_RW,
                                       .pdo_mapping = 0,
                                       .flags = 0 | CO_OBJ_FLAGS_DEF_NODEID |
                                                CO_OBJ_FLAGS_VAL_NODEID}}},
        {.name = CO_SDEV_STRING("Inhibit time EMCY"),
         .idx = 0x1015,
         .code = CO_OBJECT_VAR,
         .nsub = 1,
         .subs = (const struct co_ssub[]){{.name = CO_SDEV_STRING(
                                               "Inhibit time EMCY"),
                                           .subidx = 0x00,
                                           .type = CO_DEFTYPE_UNSIGNED16,
                                           .min = {.u16 = CO_UNSIGNED16_MIN},
                                           .max = {.u16 = CO_UNSIGNED16_MAX},
                                           .def = {.u16 = CO_UNSIGNED16_MIN},
                                           .val = {.u16 = CO_UNSIGNED16_MIN},
                                           .access = CO_ACCESS_RW,
                                           .pdo_mapping = 0,
                                           .flags = 0}}},
        // Hinzugefügt:
        {.name = CO_SDEV_STRING("COB-ID time stamp object"),
         .idx = 0x1012,
         .code = CO_OBJECT_VAR,
         .nsub = 1,
         .subs = (const struct co_ssub[]){{.name = CO_SDEV_STRING(
                                               "COB-ID time stamp object"),
                                           .subidx = 0x00,
                                           .type = CO_DEFTYPE_UNSIGNED32,
                                           .min = {.u32 = CO_UNSIGNED32_MIN},
                                           .max = {.u32 = CO_UNSIGNED32_MAX},
                                           .def = {.u32 = 0x80000100lu},
                                           .val = {.u32 = 0x80000100lu},
                                           .access = CO_ACCESS_RW,
                                           .pdo_mapping = 0,
                                           .flags = 0}}},
        {.name = CO_SDEV_STRING("Consumer heartbeat time"),
         .idx = 0x1016,
         .code = CO_OBJECT_ARRAY,
         .nsub = 2,
         .subs =
             (const struct co_ssub[]){
                 {.name = CO_SDEV_STRING("NrOfObjects"),
                  .subidx = 0x00,
                  .type = CO_DEFTYPE_UNSIGNED8,
                  .min = {.u8 = CO_UNSIGNED8_MIN},
                  .max = {.u8 = CO_UNSIGNED8_MAX},
                  .def = {.u8 = 0x01},
                  .val = {.u8 = 0x01},
                  .access = CO_ACCESS_RO,
                  .pdo_mapping = 0,
                  .flags = 0},
                 {.name = CO_SDEV_STRING("Consumer heartbeat time1"),
                  .subidx = 0x01,
                  .type = CO_DEFTYPE_UNSIGNED32,
                  .min = {.u32 = CO_UNSIGNED32_MIN},
                  .max = {.u32 = CO_UNSIGNED32_MAX},
                  .def = {.u32 = CO_UNSIGNED32_MIN},
                  .val = {.u32 = CO_UNSIGNED32_MIN},
                  .access = CO_ACCESS_RW,
                  .pdo_mapping = 0,
                  .flags = 0}}},
        {.name = CO_SDEV_STRING("Producer heartbeat time"),
         .idx = 0x1017,
         .code = CO_OBJECT_VAR,
         .nsub = 1,
         .subs = (const struct co_ssub[]){{.name = CO_SDEV_STRING(
                                               "Producer heartbeat time"),
                                           .subidx = 0x00,
                                           .type = CO_DEFTYPE_UNSIGNED16,
                                           .min = {.u16 = CO_UNSIGNED16_MIN},
                                           .max = {.u16 = CO_UNSIGNED16_MAX},
                                           .def = {.u16 = CO_UNSIGNED16_MIN},
                                           .val = {.u16 = CO_UNSIGNED16_MIN},
                                           .access = CO_ACCESS_RW,
                                           .pdo_mapping = 0,
                                           .flags = 0}}},
        {.name = CO_SDEV_STRING("Identity object"),
         .idx = 0x1018,
         .code = CO_OBJECT_RECORD,
         .nsub = 5,
         .subs =
             (const struct co_ssub[]){
                 {.name = CO_SDEV_STRING("Highest sub-index supported"),
                  .subidx = 0x00,
                  .type = CO_DEFTYPE_UNSIGNED8,
                  .min = {.u8 = CO_UNSIGNED8_MIN},
                  .max = {.u8 = CO_UNSIGNED8_MAX},
                  .def = {.u8 = 0x04},
                  .val = {.u8 = 0x04},
                  .access = CO_ACCESS_CONST,
                  .pdo_mapping = 0,
                  .flags = 0},
                 {.name = CO_SDEV_STRING("Vendor-ID"),
                  .subidx = 0x01,
                  .type = CO_DEFTYPE_UNSIGNED32,
                  .min = {.u32 = CO_UNSIGNED32_MIN},
                  .max = {.u32 = CO_UNSIGNED32_MAX},
                  .def = {.u32 = 0x00000360lu},
                  .val = {.u32 = 0x00000360lu},
                  .access = CO_ACCESS_RO,
                  .pdo_mapping = 0,
                  .flags = 0},
                 {.name = CO_SDEV_STRING("Product code"),
                  .subidx = 0x02,
                  .type = CO_DEFTYPE_UNSIGNED32,
                  .min = {.u32 = CO_UNSIGNED32_MIN},
                  .max = {.u32 = CO_UNSIGNED32_MAX},
                  .def = {.u32 = CO_UNSIGNED32_MIN},
                  .val = {.u32 = CO_UNSIGNED32_MIN},
                  .access = CO_ACCESS_RO,
                  .pdo_mapping = 0,
                  .flags = 0},
                 {.name = CO_SDEV_STRING("Revision number"),
                  .subidx = 0x03,
                  .type = CO_DEFTYPE_UNSIGNED32,
                  .min = {.u32 = CO_UNSIGNED32_MIN},
                  .max = {.u32 = CO_UNSIGNED32_MAX},
                  .def = {.u32 = CO_UNSIGNED32_MIN},
                  .val = {.u32 = CO_UNSIGNED32_MIN},
                  .access = CO_ACCESS_RO,
                  .pdo_mapping = 0,
                  .flags = 0},
                 {.name = CO_SDEV_STRING("Serial number"),
                  .subidx = 0x04,
                  .type = CO_DEFTYPE_UNSIGNED32,
                  .min = {.u32 = CO_UNSIGNED32_MIN},
                  .max = {.u32 = CO_UNSIGNED32_MAX},
                  .def = {.u32 = CO_UNSIGNED32_MIN},
                  .val = {.u32 = CO_UNSIGNED32_MIN},
                  .access = CO_ACCESS_RO,
                  .pdo_mapping = 0,
                  .flags = 0}}},
        {.name = CO_SDEV_STRING("Error behavior object"),
         .idx = 0x1029,
         .code = CO_OBJECT_ARRAY,
         .nsub = 2,
         .subs =
             (const struct co_ssub[]){
                 {.name = CO_SDEV_STRING("NrOfObjects"),
                  .subidx = 0x00,
                  .type = CO_DEFTYPE_UNSIGNED8,
                  .min = {.u8 = CO_UNSIGNED8_MIN},
                  .max = {.u8 = CO_UNSIGNED8_MAX},
                  .def = {.u8 = 0x01},
                  .val = {.u8 = 0x01},
                  .access = CO_ACCESS_RO,
                  .pdo_mapping = 0,
                  .flags = 0},
                 {.name = CO_SDEV_STRING("Error behavior object1"),
                  .subidx = 0x01,
                  .type = CO_DEFTYPE_UNSIGNED8,
                  .min = {.u8 = CO_UNSIGNED8_MIN},
                  .max = {.u8 = CO_UNSIGNED8_MAX},
                  .def = {.u8 = CO_UNSIGNED8_MIN},
                  .val = {.u8 = CO_UNSIGNED8_MIN},
                  .access = CO_ACCESS_RW,
                  .pdo_mapping = 0,
                  .flags = 0}}},
        // Hinzugefügt:
        {.name = CO_SDEV_STRING("NMT startup"),
         .idx = 0x1f80,
         .code = CO_OBJECT_VAR,
         .nsub = 1,
         .subs =
             (const struct co_ssub[]){{.name = CO_SDEV_STRING("NMT startup"),
                                       .subidx = 0x00,
                                       .type = CO_DEFTYPE_UNSIGNED32,
                                       .min = {.u32 = CO_UNSIGNED32_MIN},
                                       .max = {.u32 = CO_UNSIGNED32_MAX},
                                       .def = {.u32 = CO_UNSIGNED32_MIN},
                                       .val = {.u32 = 0x00000004lu},
                                       .access = CO_ACCESS_RW,
                                       .pdo_mapping = 0,
                                       .flags = 0}}},
        {.name = CO_SDEV_STRING("RPDO communication parameter"),
         .idx = 0x1400,
         .code = CO_OBJECT_RECORD,
         .nsub = 6,
         .subs =
             (const struct co_ssub[]){
                 {.name = CO_SDEV_STRING("highest sub-index supported"),
                  .subidx = 0x00,
                  .type = CO_DEFTYPE_UNSIGNED8,
                  .min = {.u8 = CO_UNSIGNED8_MIN},
                  .max = {.u8 = CO_UNSIGNED8_MAX},
                  .def = {.u8 = 0x05},
                  .val = {.u8 = 0x05},
                  .access = CO_ACCESS_CONST,
                  .pdo_mapping = 0,
                  .flags = 0},
                 {.name = CO_SDEV_STRING("COB-ID used by RPDO"),
                  .subidx = 0x01,
                  .type = CO_DEFTYPE_UNSIGNED32,
                  .min = {.u32 = CO_UNSIGNED32_MIN},
                  .max = {.u32 = CO_UNSIGNED32_MAX},
                  .def = {.u32 = 0x202},//0x000002fflu}, // TODO: Should be x202
                  .val = {.u32 = 0x202},//x000002fflu},
                  .access = CO_ACCESS_RW,
                  .pdo_mapping = 0,
                  .flags =
                      0 | CO_OBJ_FLAGS_DEF_NODEID | CO_OBJ_FLAGS_VAL_NODEID},
                 {.name = CO_SDEV_STRING("transmission type"),
                  .subidx = 0x02,
                  .type = CO_DEFTYPE_UNSIGNED8,
                  .min = {.u8 = CO_UNSIGNED8_MIN},
                  .max = {.u8 = CO_UNSIGNED8_MAX},
                  .def = {.u8 = 0x01},
                  .val = {.u8 = 0x01},
                  .access = CO_ACCESS_RW,
                  .pdo_mapping = 0,
                  .flags = 0},
                 {.name = CO_SDEV_STRING("inhibit time"),
                  .subidx = 0x03,
                  .type = CO_DEFTYPE_UNSIGNED16,
                  .min = {.u16 = CO_UNSIGNED16_MIN},
                  .max = {.u16 = CO_UNSIGNED16_MAX},
                  .def = {.u16 = CO_UNSIGNED16_MIN},
                  .val = {.u16 = CO_UNSIGNED16_MIN},
                  .access = CO_ACCESS_RW,
                  .pdo_mapping = 0,
                  .flags = 0},
                 {.name = CO_SDEV_STRING("compatibility entry"),
                  .subidx = 0x04,
                  .type = CO_DEFTYPE_UNSIGNED8,
                  .min = {.u8 = CO_UNSIGNED8_MIN},
                  .max = {.u8 = CO_UNSIGNED8_MAX},
                  .def = {.u8 = CO_UNSIGNED8_MIN},
                  .val = {.u8 = CO_UNSIGNED8_MIN},
                  .access = CO_ACCESS_RW,
                  .pdo_mapping = 0,
                  .flags = 0},
                 {.name = CO_SDEV_STRING("event-timer"),
                  .subidx = 0x05,
                  .type = CO_DEFTYPE_UNSIGNED16,
                  .min = {.u16 = CO_UNSIGNED16_MIN},
                  .max = {.u16 = CO_UNSIGNED16_MAX},
                  .def = {.u16 = CO_UNSIGNED16_MIN},
                  .val = {.u16 = CO_UNSIGNED16_MIN},
                  .access = CO_ACCESS_RW,
                  .pdo_mapping = 0,
                  .flags = 0}}},
        {.name = CO_SDEV_STRING("RPDO mapping parameter"),
         .idx = 0x1600,
         .code = CO_OBJECT_ARRAY,
         .nsub = 2,
         .subs =
             (const struct co_ssub[]){
                 {.name = CO_SDEV_STRING("NrOfObjects"),
                  .subidx = 0x00,
                  .type = CO_DEFTYPE_UNSIGNED8,
                  .min = {.u8 = CO_UNSIGNED8_MIN},
                  .max = {.u8 = CO_UNSIGNED8_MAX},
                  .def = {.u8 = 0x01},
                  .val = {.u8 = 0x01},
                  .access = CO_ACCESS_RO,
                  .pdo_mapping = 0,
                  .flags = 0},
                 {.name = CO_SDEV_STRING("RPDO mapping parameter1"),
                  .subidx = 0x01,
                  .type = CO_DEFTYPE_UNSIGNED32,
                  .min = {.u32 = CO_UNSIGNED32_MIN},
                  .max = {.u32 = CO_UNSIGNED32_MAX},
                  .def = {.u32 = CO_UNSIGNED32_MIN},
                  .val = {.u32 = 0x60400020lu},
                  .access = CO_ACCESS_RW,
                  .pdo_mapping = 0,
                  .flags = 0}}},
        {.name = CO_SDEV_STRING("TPDO communication parameter"),
         .idx = 0x1800,
         .code = CO_OBJECT_RECORD,
         .nsub = 7,
         .subs =
             (const struct co_ssub[]){
                 {.name = CO_SDEV_STRING("highest sub-index supported"),
                  .subidx = 0x00,
                  .type = CO_DEFTYPE_UNSIGNED8,
                  .min = {.u8 = CO_UNSIGNED8_MIN},
                  .max = {.u8 = CO_UNSIGNED8_MAX},
                  .def = {.u8 = 0x06},
                  .val = {.u8 = 0x06},
                  .access = CO_ACCESS_CONST,
                  .pdo_mapping = 0,
                  .flags = 0},
                 {.name = CO_SDEV_STRING("COB-ID used by TPDO"),
                  .subidx = 0x01,
                  .type = CO_DEFTYPE_UNSIGNED32,
                  .min = {.u32 = CO_UNSIGNED32_MIN},
                  .max = {.u32 = CO_UNSIGNED32_MAX},
                  .def = {.u32 = 0x182},//0x0000027flu} // TODO: This should be 0x182?
                  .val = {.u32 = 0x182}, //0x0000027flu},
                  .access = CO_ACCESS_RW,
                  .pdo_mapping = 0,
                  .flags =
                      0 | CO_OBJ_FLAGS_DEF_NODEID | CO_OBJ_FLAGS_VAL_NODEID},
                 {.name = CO_SDEV_STRING("transmission type"),
                  .subidx = 0x02,
                  .type = CO_DEFTYPE_UNSIGNED8,
                  .min = {.u8 = CO_UNSIGNED8_MIN},
                  .max = {.u8 = CO_UNSIGNED8_MAX},
                  .def = {.u8 = 0x01},
                  .val = {.u8 = 0x01},
                  .access = CO_ACCESS_RW,
                  .pdo_mapping = 0,
                  .flags = 0},
                 {.name = CO_SDEV_STRING("inhibit time"),
                  .subidx = 0x03,
                  .type = CO_DEFTYPE_UNSIGNED16,
                  .min = {.u16 = CO_UNSIGNED16_MIN},
                  .max = {.u16 = CO_UNSIGNED16_MAX},
                  .def = {.u16 = CO_UNSIGNED16_MIN},
                  .val = {.u16 = CO_UNSIGNED16_MIN},
                  .access = CO_ACCESS_RW,
                  .pdo_mapping = 0,
                  .flags = 0},
                 {.name = CO_SDEV_STRING("reserved"),
                  .subidx = 0x04,
                  .type = CO_DEFTYPE_UNSIGNED8,
                  .min = {.u8 = CO_UNSIGNED8_MIN},
                  .max = {.u8 = CO_UNSIGNED8_MAX},
                  .def = {.u8 = CO_UNSIGNED8_MIN},
                  .val = {.u8 = CO_UNSIGNED8_MIN},
                  .access = CO_ACCESS_RW,
                  .pdo_mapping = 0,
                  .flags = 0},
                 {.name = CO_SDEV_STRING("event timer"),
                  .subidx = 0x05,
                  .type = CO_DEFTYPE_UNSIGNED16,
                  .min = {.u16 = CO_UNSIGNED16_MIN},
                  .max = {.u16 = CO_UNSIGNED16_MAX},
                  .def = {.u16 = CO_UNSIGNED16_MIN},
                  .val = {.u16 = CO_UNSIGNED16_MIN},
                  .access = CO_ACCESS_RW,
                  .pdo_mapping = 0,
                  .flags = 0},
                 {.name = CO_SDEV_STRING("SYNC start value"),
                  .subidx = 0x06,
                  .type = CO_DEFTYPE_UNSIGNED8,
                  .min = {.u8 = CO_UNSIGNED8_MIN},
                  .max = {.u8 = CO_UNSIGNED8_MAX},
                  .def = {.u8 = CO_UNSIGNED8_MIN},
                  .val = {.u8 = CO_UNSIGNED8_MIN},
                  .access = CO_ACCESS_RW,
                  .pdo_mapping = 0,
                  .flags = 0}}},
        {.name = CO_SDEV_STRING("TPDO mapping parameter"),
         .idx = 0x1a00,
         .code = CO_OBJECT_ARRAY,
         .nsub = 2,
         .subs =
             (const struct co_ssub[]){
                 {.name = CO_SDEV_STRING("NrOfObjects"),
                  .subidx = 0x00,
                  .type = CO_DEFTYPE_UNSIGNED8,
                  .min = {.u8 = CO_UNSIGNED8_MIN},
                  .max = {.u8 = CO_UNSIGNED8_MAX},
                  .def = {.u8 = 0x01},
                  .val = {.u8 = 0x01},
                  .access = CO_ACCESS_RO,
                  .pdo_mapping = 0,
                  .flags = 0},
                 {.name = CO_SDEV_STRING("TPDO mapping parameter1"),
                  .subidx = 0x01,
                  .type = CO_DEFTYPE_UNSIGNED32,
                  .min = {.u32 = CO_UNSIGNED32_MIN},
                  .max = {.u32 = CO_UNSIGNED32_MAX},
                  .def = {.u32 = CO_UNSIGNED32_MIN},
                  .val = {.u32 = 0x60410020lu},
                  .access = CO_ACCESS_RW,
                  .pdo_mapping = 0,
                  .flags = 0}}},
        {.name = CO_SDEV_STRING("UNSIGNED32 received by slave"),
         .idx = 0x6040,
         .code = CO_OBJECT_VAR,
         .nsub = 1,
         .subs = (const struct co_ssub[]){{.name = CO_SDEV_STRING(
                                               "UNSIGNED32 received by slave"),
                                           .subidx = 0x00,
                                           .type = CO_DEFTYPE_UNSIGNED32,
                                           .min = {.u32 = CO_UNSIGNED32_MIN},
                                           .max = {.u32 = CO_UNSIGNED32_MAX},
                                           .def = {.u32 = 2},
                                           .val = {.u32 = 2},
                                           .access = CO_ACCESS_RWW,
                                           .pdo_mapping = 1,
                                           .flags = 0}}},
        {.name = CO_SDEV_STRING("UNSIGNED32 sent from slave"),
         .idx = 0x6041,
         .code = CO_OBJECT_VAR,
         .nsub = 1,
         .subs = (const struct co_ssub[]){
             {.name = CO_SDEV_STRING("UNSIGNED32 sent from slave"),
              .subidx = 0x00,
              .type = CO_DEFTYPE_UNSIGNED32,
              .min = {.u32 = CO_UNSIGNED32_MIN},
              .max = {.u32 = CO_UNSIGNED32_MAX},
              .def = {.u32 = 3},
              .val = {.u32 = 3},
              .access = CO_ACCESS_RWR,
              .pdo_mapping = 1,
              .flags = 0}}}}};
