#include "ulog.h"
#include <lely/co/nmt.h>
#include <lely/co/rpdo.h>
#include <lely/co/tpdo.h>
#include <lely/co/sdev.h>
#include <lely/co/sdo.h>
#include <lely/co/time.h>
#include <lely/util/diag.h>

#include <assert.h>
#include <time.h>
#include <stdlib.h>
#include <unistd.h> /* read(), close() */
#include <pthread.h>
#include <lely/co/dcf.h>

#include "bsp/bsp_can.h"
#include "libcia402/include/statemachine.h"
#include "callbacks/indication.h"
#include "callbacks/co_hooks.h"

#define trace(...)                                                             \
  diag_at(DIAG_DEBUG, 0, &(struct floc){__FILE__, __LINE__, 0}, __VA_ARGS__)
// Generated by `dcf2c --no-strings lpc17xx.dcf lpc17xx_sdev -o src/sdev.c`
extern const struct co_sdev lpc17xx_sdev;

int can_sock;

static inline long diff_ms(const struct timespec *a, const struct timespec *b) {
  return (a->tv_sec - b->tv_sec) * 1000L + (a->tv_nsec - b->tv_nsec) / 1000000L;
}


// Thread 2
static void *homing_fx(void* val)
{
  co_dev_t *dev = (co_dev_t*) val;
  ulog_topic_info("Homing", "Homing Loop erstellt");
  //ulog_info("[Homing] Homing Loop erstellt");
  // Wait for Mode of operation to be set to Homing
  uint32_t mode=co_sub_get_val_u32(co_dev_find_sub(dev,0x6060,0));
  while (mode != 6)
  {
    mode=co_sub_get_val_u32(co_dev_find_sub(dev,0x6060,0));
  }
  ulog_topic_info("Homing","Mode of Operation: Homing");
  // Wait for Homing Profile to be configured
  uint32_t homing_profile=co_sub_get_val_u32(co_dev_find_sub(dev,0x6098,0));
  while (homing_profile != 1)
  {
    homing_profile=co_sub_get_val_u32(co_dev_find_sub(dev,0x6098,0));
  }
  ulog_topic_info("Homing" ,"Homing Profile: Negative Position-Switch");

  // Wait for homing "start"
  while (mode != 0xF6)
  {
    mode=co_sub_get_val_u32(co_dev_find_sub(dev,0x6060,0));
  }
  ulog_topic_info("Homing","Start Homing");

  // Verify acceleration and speed
  ulog_topic_info("Homing","Acceleration=%lu, Velocity=%u",
  co_sub_get_val_u32(co_dev_find_sub(dev,0x609A,0)),
  co_sub_get_val_u32(co_dev_find_sub(dev,0x6099,0))
);
  while (1)
  {
    // Wait for stop conditions:
    // Fault Reaction active
    // GPIO active
    // Software Limit reached
    // Set "Homing attained", "Homing Permormed", "Target rea-ched"
  }
}

void on_time_cb(co_time_t *time, const struct timespec *tp, void *data) {
  (void)time;
  (void)data;

  // Update the wall clock, _not_ the monotonic clock used by the CAN
  // network.
  clock_settime(CLOCK_REALTIME, tp);
}
int main(int argc,char **argv) {

  char* can_if=argv[1];
  char* dcf=argv[2];
  printf("interface = %s, dcf = %s\r\n",can_if,dcf);
  ulog_topic_add("Homing", ULOG_OUTPUT_ALL, ULOG_LEVEL_INFO);
  ulog_topic_add("TPDO",ULOG_OUTPUT_ALL,ULOG_LEVEL_INFO);
  ulog_topic_add("RPDO",ULOG_OUTPUT_ALL,ULOG_LEVEL_INFO);
  ulog_topic_add("CAN",ULOG_OUTPUT_ALL,ULOG_LEVEL_INFO);

  can_sock = can_open("vcan0");

  can_net_t *net = can_net_create();
  assert(net);
  can_net_set_send_func(net, &on_can_send, NULL);

  struct timespec now = {0, 0};
  struct timespec last = {0, 0};
  struct timespec tx_time = {0, 0};

//  clock_gettime(CLOCK_MONOTONIC, &now);
//  can_net_set_time(net, &now;
  timespec_get(&now, TIME_UTC);
  can_net_set_time(net, &now);

#if USE_SDEV
  // Create a dynamic object dictionary from the static object dictionary.
  co_dev_t *dev = co_dev_create_from_sdev(&lpc17xx_sdev);

// RPDO_1 : 0x1800 + Mapping@ 0x1a00
  co_tpdo_t *tpdo_1 = co_tpdo_create(net, dev, 1);
  if (tpdo_1 == NULL) {
    trace("tdpo 1 not created");
  }

  if (co_tpdo_start(tpdo_1) != 0) {
    trace("could not start tpdo");
  }
// TPDO_1 : 0x1600 + Mapping@ 0x1600
  co_rpdo_t *rpdo_1 = co_rpdo_create(net, dev, 1);
    if (rpdo_1 == NULL) {
      trace("rdpo 1 not created");
    }

  if (co_rpdo_start(rpdo_1) != 0) {
    trace("could not start rpdo");
  }

  if (co_rpdo_sync(rpdo_1, 1) != 0) {
    trace("rpdo could not be configured with sync");
  }

  void *pdata;
    co_rpdo_set_ind(rpdo_1, my_rpdo_indication, pdata);

  void *p_tx_data;
  if (co_tpdo_sync(tpdo_1, 1) != 0) {
   trace("sync service not working");
  }
  co_tpdo_set_ind(tpdo_1, tpdo_indication, p_tx_data);

#else
  co_dev_t *dev = co_dev_create_from_dcf_file(dcf);
#endif
  assert(dev);
  // Create the CANopen NMT service.
  co_nmt_t *nmt = co_nmt_create(net, dev);
  assert(nmt);
  co_time_t *time = co_time_create(net,dev);
  ulog_error("%s",errc2str(get_errc()));
  assert(time);

  co_nmt_cs_ind(nmt, CO_NMT_CS_RESET_NODE);
  co_nmt_set_cs_ind(nmt, &on_nmt_cs, NULL);
  uint32_t val = 0;
  co_obj_t *obj = co_dev_find_obj(dev, 0x6040);
  co_obj_set_val(obj, 0x00, &val, sizeof(val));
  co_nmt_on_sync(nmt, 1);
  co_nmt_set_sync_ind(nmt, sync_indication, NULL);
  co_time_set_ind(co_nmt_get_time(nmt), &on_time_cb, NULL);

  // Threads
  pthread_t homing_thread;
  int rc = pthread_create( &homing_thread, NULL, &homing_fx, (void*)dev );
  if( rc != 0 ) {
    ulog_error("Konnte Thread 1 nicht erzeugen\n");
    return EXIT_FAILURE;
  }
  for (;;) {
    co_obj_t * obj = co_dev_find_obj(dev, 0x6040);
    uint32_t ctrl_word=co_sub_get_val_u32(co_dev_find_sub(dev,0x6040,0));
    run_transition(ctrl_word);
    uint16_t statusword=get_statusword_lowbyte(get_state());
    obj = co_dev_find_obj(dev, 0x6041);
    co_obj_set_val(obj, 0x00,&statusword, sizeof(val));
    //ulog_info("[Main] : statusword = %04x, controlword %04x",statusword,ctrl_word);
    // Update the CAN network clock.
//    clock_gettime(CLOCK_MONOTONIC, &now);
//    can_net_set_time(net, &now);
    timespec_get(&now, TIME_UTC);
    can_net_set_time(net, &now);
    // Process any received CAN frames.
    struct can_msg msg;
    int n_frames = can_recv(&msg, 1);
    if (n_frames != 0) {
      can_net_recv(net, &msg);
    }

    if (diff_ms(&now, &last) >= 1000) {
      val++;
      co_obj_set_val(obj, 0x00, &val, sizeof(val));
      last = now;
    }
    // TODO: Update object dictionary.
  }
  co_nmt_destroy(nmt);
  co_dev_destroy(dev);
  can_net_destroy(net);
  return 0;
}