#include "ulog/ulog.h"

#include <lely/co/nmt.h>
#include <lely/co/rpdo.h>
#include <lely/co/sdev.h>
#include <lely/co/sdo.h>
#include <lely/co/time.h>
#include <lely/co/tpdo.h>

#include <assert.h>
#include <errno.h>
#include <stdlib.h>
#include <time.h>

// #include <lely/io2/linux/can.h>
#include "bsp/bsp_can.h"
#include <lely/util/diag.h>

#include  "libcia402/include/statemachine.h"
#include <unistd.h> /* read(), close() */
#define trace(...)                                                             \
  diag_at(DIAG_DEBUG, 0, &(struct floc){__FILE__, __LINE__, 0}, __VA_ARGS__)

#ifndef CAN_BITRATE
#define CAN_BITRATE 125000
#endif

static int on_can_send(const struct can_msg *msg, void *data);
int can_recv(struct can_msg *ptr, size_t n);

static void on_nmt_cs(co_nmt_t *nmt, co_unsigned8_t cs, void *data);
static void on_time(co_time_t *time, const struct timespec *tp, void *data);
// Generated by `dcf2c --no-strings lpc17xx.dcf lpc17xx_sdev -o src/sdev.c`
extern const struct co_sdev lpc17xx_sdev;

int can_sock;

static co_rpdo_ind_t my_rpdo_indication;
static co_tpdo_ind_t tpdo_indication;
static co_nmt_sync_ind_t sync_indication;

static void my_rpdo_indication(co_rpdo_t *pdo, co_unsigned32_t ac,
                               const void *ptr, size_t n, void *data) {
  if (ac != 0) {
    /* Fehler beim Empfang */
    trace("RPDO error, abort code: 0x%08X\n", ac);
    return;
  }

  /* Erfolgreicher Empfang */
  trace("RPDO received: %zu bytes\n", n);

  const uint8_t *bytes = (const uint8_t *)ptr;
  for (size_t i = 0; i < n; ++i) {
    trace("Byte %zu: 0x%02X\n", i, bytes[i]);
  }

  /* Optional: benutzerspezifische Daten */
  if (data) {
    trace("User data pointer: %p\n", data);
  }
}

static void tpdo_indication(co_tpdo_t *pdo, co_unsigned32_t ac, const void *ptr,
                            size_t n, void *data) {
  if (ac != 0) {
    /* Fehler beim Empfang */
    ulog_info("[TPDO] error, abort code: 0x%08X\n", ac);
    return;
  }

  ulog_info("[TPDO] tx send %i bytes", n);

  const uint8_t *bytes = (const uint8_t *)ptr;
  for (size_t i = 0; i < n; ++i) {
    ulog_info("[TPDO] Byte %zu: 0x%02X\n", i, bytes[i]);
  }
}

static void sync_indication(co_nmt_t *nmt, co_unsigned8_t cnt, void *data) {
  ulog_info("[NMT] : received sync indication for count %i", cnt);
}
static inline long diff_ms(const struct timespec *a, const struct timespec *b) {
  return (a->tv_sec - b->tv_sec) * 1000L + (a->tv_nsec - b->tv_nsec) / 1000000L;
}

int main(void) {
  ulog_topic_config(true);
  can_sock = can_open("vcan0");
  //	can_init(CAN_BITRATE);

  can_net_t *net = can_net_create();
  assert(net);
  can_net_set_send_func(net, &on_can_send, NULL);

  struct timespec now = {0, 0};
  struct timespec last = {0, 0};
  struct timespec tx_time = {0, 0};

  clock_gettime(CLOCK_MONOTONIC, &now);
  can_net_set_time(net, &now);

  // Create a dynamic object dictionary from the static object dictionary.
  co_dev_t *dev = co_dev_create_from_sdev(&lpc17xx_sdev);
  assert(dev);
  // Create the CANopen NMT service.
  co_nmt_t *nmt = co_nmt_create(net, dev);
  assert(nmt);

  co_nmt_cs_ind(nmt, CO_NMT_CS_RESET_NODE);
  co_nmt_set_cs_ind(nmt, &on_nmt_cs, NULL);
  co_time_set_ind(co_nmt_get_time(nmt), &on_time, NULL);
// RPDO_1 : 0x1800 + Mapping@ 0x1a00
  co_tpdo_t *tpdo_1 = co_tpdo_create(net, dev, 1);
  if (tpdo_1 == NULL) {
    trace("tdpo 1 not created");
  }

  if (co_tpdo_start(tpdo_1) != 0) {
    trace("could not start tpdo");
  }
// TPDO_1 : 0x1600 + Mapping@ 0x1600
  co_rpdo_t *rpdo_1 = co_rpdo_create(net, dev, 1);
    if (rpdo_1 == NULL) {
      trace("rdpo 1 not created");
    }

  if (co_rpdo_start(rpdo_1) != 0) {
    trace("could not start rpdo");
  }

  if (co_rpdo_sync(rpdo_1, 1) != 0) {
    trace("rpdo could not be configured with sync");
  }

  void *pdata;
    co_rpdo_set_ind(rpdo_1, my_rpdo_indication, pdata);

  void *p_tx_data;
  void *p_sync_data;
  if (co_tpdo_sync(tpdo_1, 1) != 0) {
   trace("sync service not working");
  }
  co_tpdo_set_ind(tpdo_1, tpdo_indication, p_tx_data);
  uint32_t val = 0;
  co_obj_t *obj = co_dev_find_obj(dev, 0x6040);
  co_obj_set_val(obj, 0x00, &val, sizeof(val));
  co_nmt_on_sync(nmt, 1);
  co_nmt_set_sync_ind(nmt, sync_indication, p_sync_data);

  for (;;) {
    co_obj_t * obj = co_dev_find_obj(dev, 0x6040);
    uint32_t ctrl_word=co_sub_get_val_u32(co_dev_find_sub(dev,0x6040,0));
    run_transition(ctrl_word);
    uint16_t statusword=get_statusword_lowbyte(get_state());
    obj = co_dev_find_obj(dev, 0x6041);
    co_obj_set_val(obj, 0x00,&statusword, sizeof(val));
    ulog_info("[Main] : statusword = %04x, controlword %04x",statusword,ctrl_word);
    // Update the CAN network clock.
    clock_gettime(CLOCK_MONOTONIC, &now);
    can_net_set_time(net, &now);

    // Process any received CAN frames.
    struct can_msg msg;
    int n_frames = can_recv(&msg, 1);
    if (n_frames != 0) {
      can_net_recv(net, &msg);
    }

    if (diff_ms(&now, &last) >= 1000) {
      val++;
      co_obj_set_val(obj, 0x00, &val, sizeof(val));
      last = now;
    }
    // TODO: Update object dictionary.
  }

  co_nmt_destroy(nmt);
  co_dev_destroy(dev);
  can_net_destroy(net);
  return 0;
}

static int on_can_send(const struct can_msg *msg, void *data) {
  uint32_t can_id;
  if (!msg || !data) {
  }
  can_id = msg->id;
  if (can_id == 0x27f){
//    can_id=0x182;
  }
  if (msg->flags & CAN_FLAG_RTR) {
    can_id |= CAN_RTR_FLAG;
    ulog_info("[CAN] tx: Id with added RTR-Flag");
  }

  /* Datenlänge prüfen */
  if (msg->len > CAN_MAX_LEN) {
    trace("CAN_MAX_LEN < msg size");
  }
  int err = can_send(can_sock, can_id, msg->len, msg->data);
  ulog_info("[CAN] tx: %s %4x [%i]", "vcan0", can_id, msg->len);
}

int can_recv(struct can_msg *ptr, size_t n) {
  struct can_frame frame;
  struct can_msg *msg;
  ssize_t nbytes;

  if (!ptr || n == 0 || can_sock < 0) {
    errno = EINVAL;
    return -1;
  }

  /* Genau ein Frame lesen (blockierend) */
  nbytes = read(can_sock, &frame, sizeof(frame));
  if (nbytes < 0) {
    /* errno bleibt gesetzt */
    return -1;
  }

  if ((size_t)nbytes < sizeof(struct can_frame)) {
    errno = EIO;
    return -1;
  }

  msg = &ptr[0];
  memset(msg, 0, sizeof(*msg));

  /* Identifier */
  if (frame.can_id & CAN_EFF_FLAG) {
    msg->flags |= CAN_FLAG_IDE;
    msg->id = frame.can_id & CAN_MASK_EID;
  } else {
    msg->id = frame.can_id & CAN_MASK_BID;
  }

  /* RTR */
  if (frame.can_id & CAN_RTR_FLAG) {
    msg->flags |= CAN_FLAG_RTR;
    msg->len = frame.can_dlc;
  } else {
    msg->len = frame.can_dlc;
    memcpy(msg->data, frame.data, frame.can_dlc);
  }
  return 1;
}

static void on_nmt_cs(co_nmt_t *nmt, co_unsigned8_t cs, void *data) {
  (void)data;

  switch (cs) {
  case CO_NMT_CS_START:
    // Reset the TIME indication function, since the service may
    // have been restarted.
    co_time_set_ind(co_nmt_get_time(nmt), &on_time, NULL);
    break;
  case CO_NMT_CS_STOP:
    break;
  case CO_NMT_CS_ENTER_PREOP:
    co_time_set_ind(co_nmt_get_time(nmt), &on_time, NULL);
    break;
  case CO_NMT_CS_RESET_NODE:
    // Initiate a system reset.
    exit(0);
    break;
  case CO_NMT_CS_RESET_COMM:
    break;
  }
}

static void on_time(co_time_t *time, const struct timespec *tp, void *data) {
  (void)time;
  (void)data;

  // Update the wall clock, _not_ the monotonic clock used by the CAN
  // network.
  clock_settime(CLOCK_REALTIME, tp);
}