jobs:
  build:
    runs-on: docker
    container:
      image: ubuntu:24.04

    steps:
      - name: Update & Install Dependencies
        run: |
          apt-get update -y
          apt-get install -y software-properties-common
          add-apt-repository -y ppa:lely/ppa
          apt-get update -y
          apt-get install -y liblely-coapp-dev liblely-co-tools python3-dcf-tools

      - name: Test Runner
        run: |
          echo "Running in Ubuntu Noble Docker container"
          uname -a
